server:
  port: 9002

spring:
  kafka:
    consumer:
      bootstrap-servers: ${application.kafka.bootstrap-servers}
      group-id: ${application.kafka.group-id}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ${application.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  kafka:
    bootstrap-servers: broker-1:9092,broker-2:9093,broker-3:9094
    group-id: group_id
    topic: topic-lab